README.md
We need a support notice so that users know the extension is only community supported. 
Added the support notice to the readme
=> Add support notice to readme

snippets/spring-data/analytics.json, snippets/spring-data/bootstrapping.json, snippets/spring-data/fts.json, snippets/spring-data/kvops.json, snippets/spring-data/managementapi.json, snippets/spring-data/query.json, snippets/spring-data/subdocops.json, snippets/spring-data/transactions.json
Closes #86.
snippets for spring-data
These are from the visx file that Babar gave me to review.   It looks like he never merged the spring-data directory into the repository.   I don't know what else is required for the @cbsdxxxx snippets to work.  Do entries also need to be added to package.json?
=> VSCode-86 - add snippets for spring-data-couchbase

src/model/CollectionNode.ts
A small change in catch block, checking if the error is PlanningFailureError
=> Da 136 unable to load documents under collections

package.json, src/extension.ts, src/model/CollectionNode.ts, src/model/IBucket.ts, src/webViews/webViewProvider.ts
[](url)## Describe the problem this PR is solving
Add Bucket administrative information
Added a Get Info option to the context menu to get the bucket information
We are using a function getBucket() to get the Bucket metadata. 
The representation is in form of Web View and the final result is shown in Tabular form as follows:
=> Da 151 feature add bucket administrative information

src/extension.ts
When we create a new collection, it does not automatically refresh the UI and update in folder view.
We expect to see the new collection when we create it and we are doing it by calling parent bucket of that collection.
Also the PR contains some error handing where we are handling the issues with DocumentNotFound Error.
=> Da#94 created collection should be automatically visible

src/model/ClusterConnectionNode.ts, src/webViews/connectionScreen.webview.ts
It is required to include the "Connection Identifier" while creating a new connection. This identifier is used as the title instead of the previous format "user@ConnectionString" in order to improve the appearance of the listing.
=> Da#131 use connection identifier as title of connection

package.json, src/webViews/connectionScreen.webview.ts
Remove all unnecessary command from palette.
=> Remove unnecessary command from command palette

src/extension.ts
=> DA#146: Modified: Change the Document Name to Document Id

src/util/connections.ts
If the connection is already exist the user tries to connect to same, the same connection is getting replaced with the new connection identifier (Name of the connection) and user might get confused about it.
=> Notify user if he is trying to connect to connect to existing cluster

src/util/connections.ts, src/webViews/connectionScreen.webview.ts
The progress bar goes like below while trying to connect to cluster:
On successfully establishing the connection
=> Show the Progress Bar saying Try to connect to Cluster and an information message says Connection Successfully established while connecting to Cluster

README.md, package.json
=> Da#157 Update readme to let user know that openssl is a requirement

src/extension.ts, src/util/logger.ts
Logger Added to catch unhandled exceptions
=> Logger Added to catch unhandled exceptions

package.json
Remove refresh connection on unnecessary context menu bar
=> Remove refresh connection on unnecessary context menu bar

src/util/connections.ts
Handle Error while connecting to cluster to already existing cluster if the connection failed we should show the troubleshooting link.
=> Handle Error while connecting to cluster to already existing cluster

images/dark/info-icon.svg, images/light/info-icon.svg, src/model/BucketNode.ts, src/model/ClusterConnectionNode.ts, src/model/CollectionDirectory.ts, src/model/CollectionNode.ts, src/model/IndexDirectory.ts, src/model/IndexNode.ts, src/model/InformationNode.ts
When buckets, collections, scopes and documents are not available to list, we show an item saying No Bucket(Item) available.
=> Da#181 display no item available if folder is empty

package.json, src/model/CollectionNode.ts
Remove delete option from the default collection
=> Remove delete option from the default collection

src/extension.ts
Validation for scope and collection name
=> Validation for scope and collection name

README.md
Added Installation information and troubleshoot information
=> Add tips for installation and Troubleshoot information

src/webViews/connectionScreen.webview.ts
In case connection fails, we should be able to persist the connection
=> DA#201: Modified: Persist checkbox in case connection fails

package-lock.json, package.json, src/extension.ts
Refresh Tree when document over cloud/UI is deleted
=> Refresh Tree when document over cloud/UI is deleted

src/model/IndexDirectory.ts, src/util/indexUtils.ts
=> DA#227: Added: Utilize getIndexDefinition function to get index definition for capella cluster

.github/workflows/test.yml, package.json
Adds a new workflow that executes extension tests on push to any branch.
- Adds new test workflow
- Updates the pretest script to compile the typescript files
=> Add test workflow

src/reactViews/app/bootstrap.tsx, src/reactViews/app/custom/query-stats/query-stats.scss, src/reactViews/app/custom/query-stats/query-stats.tsx, src/reactViews/app/index.scss, src/workbench/queryWorkbench.ts, src/workbench/workbenchWebviewProvider.ts
=> Da#238 implement theming in workbench

package.json
=> DA#277: Added: Run command and icon position

src/workbench/queryWorkbench.ts
Selected Query should run on workbench
=> DA#282: Modified: Selected Query should run on workbench

package.json, src/commands/extensionCommands/commands.ts, src/commands/indexes/checkAndCreatePrimaryIndex.ts, src/extension.ts, src/model/CollectionNode.ts, src/model/IndexDirectory.ts, src/model/InformationNode.ts
Primary Index Creation fix. Now primary index is created by showing nodeItem. Which can be clicked to show modal for creating index
=> DA-285 fixes primary index creation 

src/reactViews/app/bootstrap.tsx, src/reactViews/app/components/visual-explain-plan/visual-explain-plan.tsx
=> Da#291 height of capella components fixed

src/util/constants.ts, src/workbench/workbenchWebviewProvider.ts
Persist Query Result in Memory
=> DA#293: Added: Persist Query Result in Memory

src/commands/collections/createCollection.ts, src/commands/scopes/createScope.ts
=> DA#305: BugFix: Handle Errors

CHANGELOG.md, README.md
=> Da#308 update readme changelog

src/commands/tools/dataImport.ts, src/tools/CBExport.ts
Fix Bugs:
1. Collections and scope field not adjusting to spaces and newline characters
2. CB Export -> path separator for windows was not present, might have broken it
=> Da-326 cb import sometimes collection and scope field can be blank

src/commands/tools/dataImport.ts, src/extension.ts, src/pages/Tools/DataExport/dataExport.ts, src/tools/CBExport.ts, src/tools/CBImport.ts
Hide password in environment variables
=> Da 329 password is visible inside terminal for cb import export

.github/workflows/ci.yml
Fix the github actions build for windows
=> DA-335 fix GitHub actions windows build

.github/workflows/ci.yml, package-lock.json, package.json, src/tools/CBImport.ts
1. Fix Windows Build
2. Add quotes to delimiter as it was failing on windows
=> Version 1.1.1

package-lock.json, package.json, src/commands/documents/filterDocuments.ts, src/commands/iq/chat/iqChatHandler.ts, src/model/CollectionNode.ts
=> V2 bug fix

.vscodeignore, package-lock.json, package.json, src/commands/collections/removeCollection.ts, src/commands/documents/clearDocumentFilter.ts, src/commands/documents/filterDocuments.ts, src/commands/indexes/checkAndCreatePrimaryIndex.ts, src/commands/iq/iqLoginhandler.ts, src/handlers/handleCLIDownloader.ts, src/handlers/versionConfig.ts, src/model/BucketNode.ts, src/model/ClusterConnectionNode.ts, src/model/CollectionNode.ts, src/model/DocumentNode.ts, src/model/IndexDirectory.ts, src/model/IndexNode.ts, src/model/SchemaDirectory.ts, src/model/ScopeNode.ts, webpack.config.js
=> DA-374 package size inconsistency

src/commands/tools/dataImport.ts, src/commands/tools/ddlExport/ddlExport.ts, src/pages/FavoriteQueries/FavoriteQueries.ts, src/pages/Tools/DataExport/dataExport.ts, src/pages/Tools/MdbMigrate/mdbMigrate.ts, src/pages/overviewCluster/overviewCluster.ts, src/util/OverviewClusterUtils/ClusterOverviewGeneralTab.ts, src/util/OverviewClusterUtils/getOverviewClusterData.ts, src/util/connections.ts, src/util/constants.ts, src/webViews/connectionScreen.webview.ts, src/workbench/queryWorkbench.ts
Webview Resets on tab change Bug Fix
Change Naming on connection Page
Show cluster type (capella or self managed) in cluster overview
=> Da 377 webview resets bug fix

images/dark/named-parameters.svg, images/light/named-parameters.svg, package.json, src/commands/extensionCommands/commands.ts, src/extension.ts, src/pages/namedParameters/namedParameters.ts, src/util/constants.ts, src/util/favoriteQuery.ts, src/util/namedParameters.ts, src/webViews/favoriteQueries.webiew.ts, src/webViews/namedParameters.webview.ts, src/workbench/queryWorkbench.ts
Add support for named parameters
=> DA-442 add named parameter support

package.json
=> DA-459 add n1ql file support

package.json, src/commands/documents/contributor/autoCompleteContributor.ts, src/extension.ts
Adds document auto Complete feature from schema
=> Add document autoComplete feature

src/util/namedParameters.ts
Fix for bug: https://github.com/Couchbase-Ecosystem/VSCode-Couchbase/issues/411
=> Fix query named params bug to support data type

src/util/OverviewClusterUtils/ClusterOverviewGeneralTab.ts, src/util/OverviewClusterUtils/OverviewClusterHelper.ts
Fix: Check all services from all nodes and not just first node.
=> Update get services to check all nodes

src/reactViews/app/bootstrap.tsx, src/reactViews/app/components/data-grid/data-grid.tsx, src/reactViews/app/components/data-table/array-cell/array-cell.tsx, src/reactViews/app/components/data-table/data-table.tsx, src/reactViews/app/components/data-table/data-table.types.ts, src/reactViews/app/components/data-table/data-table.utils.ts
Fix for issue 412- Data Table Result does not show all Data
=> Da 412 fix query data table view

src/extension.ts, src/handlers/handleQueryContextStatusbar.ts, src/notebook/controller.ts, src/pages/queryContext/queryContext.ts, src/util/queryContextUtils.ts
Add support for query context on sql++ notebook
=> Add query context to sql++ notebook

package-lock.json, package.json, src/commands/cbshell/cbShell.ts, src/extension.ts, src/handlers/handleCLIDownloader.ts, src/handlers/versionConfig.ts, src/tools/CBShell.ts, src/util/connections.ts, src/util/events/connectionEvents.ts
Adds support for CB Shell on connect
=> Cbshell support

README.md
To show the images on Azure Data Studio changes the images link here.
=> DA-596 Modified Change the image links to github raw links

package-lock.json, package.json, src/workbench/queryWorkbench.ts
=> Da 431 fix query workbench crash

package.json, src/commands/extensionCommands/commands.ts, src/extension.ts, src/handlers/handleCLIDownloader.ts, src/handlers/versionConfig.ts, src/pages/Tools/HuggingFaceMigrate/huggingFaceMigrate.ts, src/tools/HFMigrate.ts, src/util/constants.ts, src/webViews/tools/huggingFaceImporter.webview.ts
=> Da 604 tool to convert hugging face dataset to couchbase

src/handlers/handleCLIDownloader.ts, src/handlers/versionConfig.ts
=> Update HF version

src/util/workbench/stripComments.ts, src/workbench/queryWorkbench.ts
=> Da-715 add support for scripts in the query workbench

package-lock.json, package.json
=> Package version update

package-lock.json, package.json, src/workbench/queryWorkbench.ts
=> Fix Timeout in Multiple queries

package-lock.json, package.json, src/commands/queryTimeout/setQueryTimeout.ts, src/workbench/queryWorkbench.ts
=> Timeout fixed

README.md
=> Add support policy section to README

README.md
=> Update Support Policy header to h2

src/commands/assistant/assistantRestAPI.ts, src/commands/assistant/assistantWebviewProvider.ts, src/reactViews/assistant/pages/chatscreen/assistantChat.tsx, src/reactViews/assistant/utils/ChatAction.tsx
- Adds feedback (thumbs up & down along with feedback message option) to Cb assistant
=> Add feedback to cb assistant

src/reactViews/assistant/pages/chatscreen/assistantChat.tsx, src/reactViews/iq/pages/chatscreen/IqChat.tsx
=> DA-977 text editor is coping the html element styl

package-lock.json, package.json
=> Update Package Version

package-lock.json, package.json, src/participant/participant.ts
=> DA-1014: Modified Document End point change
