Couchbase-Ecosystem/VSCode-Couchbase

src/test/runTest.ts
Fixes the vscode/test-electron import used to run tests.
- Closes #74 
- Fix import to use "@vscode/test-electron"
=> Update vscode/test-electron import

package-lock.json, package.json, scripts/rebuildElectron.js, src/extension.ts, src/model/BucketNode.ts, src/model/ScopeNode.ts
Add support for creating and removing scopes and collections. The commands are available via the tree view when right-clicking on the appropriate item.
eg bucket can create scopes, scopes can create collections
- Closes #21 
- Closes #23 
- Closes #24 
- Closes #26
- Adds new create scope, create collection, remove scope and remove scope commands
- Wires up new commands into context menus
=> Add support for creating and removing Scopes & Collections

src/util/connections.ts
Use the `couchbase://` scheme to connect to Couchbase clusters.
- Use `couchbase://` as the example cluster scheme when creating a new
=> Use couchbase scheme prefix when creating connections

src/model/CollectionNode.ts
The document count for a collection should be abbreviated for larger numbers.
For example, 1k, 100k, 1m, etc
Until 999 we show the unabbreviated version. After that we can show 1k-> 1000, 1.1k -> 1100, 1.2k -> 1230
=> DA#28: Added: Document count should be abbreviated

src/model/BucketNode.ts, src/model/ClusterConnectionNode.ts, src/model/CollectionNode.ts, src/model/DocumentNode.ts, src/model/ScopeNode.ts
It's sometimes useful to have access to the parent node of the currently selected node, for example to refresh a list of available documents after creating a new document.
- Update the tree node implementations to receive their parent node as a constructor arg
- Includes some file formatting automatically applied upon saving
NOTE: This PR just updated the tree nodes to receive their parent, it does not use it yet. Future PRs will use utilise the parent nodes.
=> Pass parent node as constructor argument to other nodes

src/extension.ts
Refresh collections not working
On click on refresh collections the bucket is getting refreshed so that it could refresh whole tree.
=> DA#95: Modified: Fix refresh collections

src/model/ClusterConnectionNode.ts
When connecting to multiple clusters, the specific status of each connection (active or inactive) is not indicated. It is possible to view either all active connections or all inactive connections
After Bugfix:
=> DA#110: Bugfix: Specific status of each connection should be indicated

package.json, src/extension.ts, src/notebook/controller.ts, src/notebook/notebook.ts, src/notebook/serializer.ts, src/util/constants.ts
Creating a query notebook functionality similar to Jupyter Notebook. It would allow users to write and run multiple queries in a single document with interactive cells containing commands that can be executed independently of one another. This feature would provide a more user-friendly way to work with queries, and greatly improve productivity when working with Couchbase databases.
A query notebook would also have various benefits such as:
Composing and documenting complex queries easily.
Saving and loading queries from past sessions or documents.
Giving users the option to directly copy an
d paste queries to other files.
=> Da#134 create query notebook for couchbase

src/notebook/controller.ts
When we attempt to execute a query on a notebook with an inactive connection, the system will make an effort to retrieve and display the output and stay in that state only, instead of generating an error message.
Throw an error if connection is not established.
=> In the absence of any database connectivity, a Query Notebook ought to generate an error message when a query is executed

src/extension.ts
When we create a new document and provide an Id that already exists (hotel_10025) , It is giving conflict with the document that is in server is now solved and the current behaviour is simply opening the already existing document.
=> Conflict when we create a new document and provide an Id that already exists should be removed

README.md, package-lock.json, package.json
This PR will fix builds with Windows 10 and 11
This PR changes the version of cmake-js to version 6.3.2.  This version also adds in the library node-addon-api because without it you will get errors when building the Couchbase Node SDK on older versions of cmake-js than 7.x.
The readme was updating warning people to not upgrade to version 7.x of cmake-js because that will break windows builds.
=> fixed for Windows builds

src/util/connections.ts, src/util/constants.ts, src/webViews/connectionScreen.webview.ts
Is your feature request related to a problem? Please describe.
Currently, when you are connecting to a server you need to have the scheme, which basically only define if the connection is secured or not.
Describe the solution you'd like
Scheme is not needed here, to make it more streamlined, all we need is the connection string and a checkbox, whether to use secure or not.
Also handle the case If the user enters a connection string with couchbase:// or couchbases:// by removing them.
=> Connection string should not contain scheme, but "use secure" checkbox

src/webViews/connectionScreen.webview.ts
- Check the "Use Secure Connection" checkbox if user is entering capella URL
- Change "Secure" to "Use Secure Connection"
=> Check the "Use Secure Connection" checkbox if user is entering capella URL

src/model/ScopeNode.ts
The default scope cannot be dropped. The default collection can be dropped, by means of either the Couchbase CLI, or the REST API. So we should avoid user seeing _default scope
=> The default scope can not have delete option

src/util/connections.ts
- If user try to connect to existing connection, it will ask user to delete the connection first as it already exist or connect to existing connection
- User will get two choices "Continue to Existing" and "Cancel"
- User needs to delete the cluster by itself
=> Remove checking connection before saving and the connection should not be saved if it fails

src/extension.ts, src/model/BucketNode.ts, src/model/ClusterConnectionNode.ts, src/model/CollectionDirectory.ts, src/model/CollectionNode.ts, src/model/IndexDirectory.ts, src/util/connections.ts
To avoid the need for manual cluster connection refresh and ensure that documents load properly, the connection will be automatically refreshed in the event of a FileNotFound scenario. 
Initially, the user won't be able to open the document, but the user will be able to open the document next time by clicking on it.
=> Refresh the connection automatically when FileNotFound scenario occur

src/model/CollectionNode.ts, src/model/InformationNode.ts
The information message will only say "No index available" but we hover over that node we can see the full warning saying
"No indexes available to list the documents in this collection"
=> Show no index available when no indexes are available to list the document for a collection

src/extension.ts
Fixing two bugs:
1. When we hover over a document and delete it, it was not updating in the tree immediately.
2. When we search a document, the URI_to_CAS_map should get updated
=> Bugfix delete document failure when hover and delete and update URI when search a document

package-lock.json, package.json, src/extension.ts, src/webViews/sampleProjects.webview.ts
Adds a sample project workflow to allow extension uses to clone a Couchbase sample project and open / add it to their workspace. The extension asks for a project name and local folder to put the example then downloads the example. Once the example has been downloaded, the extension asks if they would like to open the example or add to the current workspace.
- Closes #139 
- Adds gitly as extension dependency
- Add and wire up new action in package.json & extension.js
- Add webview that shows a list of sample projects grouped by language
- Add workflow to the click event of selecting one of the examples
TODO:
=> Add sample project workflow

jest.config.js, package-lock.json, package.json, src/commands/documents/createDocument.ts, src/commands/documents/removeDocument.ts, src/commands/extensionCommands/commands.ts, src/extension.ts, src/handlers/handleSaveDocument.ts, src/model/BucketNode.ts, src/model/ClusterConnectionNode.ts, src/model/CollectionNode.ts, src/model/IndexDirectory.ts, src/model/SchemaDirectory.ts, src/model/ScopeNode.ts, src/tools/MDBMigrate.ts, src/tree/ClusterConnectionTreeProvider.ts, src/util/cacheService/cacheService.test.ts, src/util/cacheService/cacheService.ts, src/util/connections.ts, src/util/constants.ts, src/util/util.ts, src/webViews/tools/mdbMigrate.webview.ts, tsconfig.json
This PR majorly updates the Cache service and tree nodes with the following:
- Updates the cache service to handle refresh of cache when required.
- Update the tree nodes to refresh each time user clicks on the node(previously used to fetch from vs code builtin cache).
- Basic tests for refresh cache.
- Fixes the mongoDB Migrate URI bug.
=> Update Cache service to handle refresh + add few tests
